name: karakter
favicon: null
layout_spectrum: 0.08326
typography_spectrum: 0.32504
title: KARAKTER
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ed1c24'
    - '#ffffff'
    - '#ff0000'
    - '#bf0000'
    - '#000000'
  brandStrength: 0.9375
  lightness: 0.1875
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
